# This file sets the configuration of the 'Product' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        # the configuration of this entity is very verbose because it's used as
        # an example to show all the configuration options available for entities
        # check out the configuration of the other entities to see how concise
        # can be the configuration of your backend
        Machine:
            class: AppBundle\Entity\Machine
            label: 'Machine'
            list:
                fields:
                    - id
                    - description
                    - { property: 'cod', label: 'cod' }
                    - { property: 'imageFront', label: 'imageFront', type: 'image', base_path: '%app.path.product_images%' }
                    - enabled
                    - { property: 'price', format: '%.2f €', label: 'price', css_class: text-right }
                    - { property: 'adminColorPageCost', format: '%.5f €', label: 'adminColorPageCost',  css_class: text-right}
                    - { property: 'colorPageCost', label: 'colorPageCost', format: '%.5f €', css_class: text-right}
                    - { property: 'adminBlackPageCost', label: 'adminBlackPageCost', format: '%.5f €', css_class: text-right}
                    - { property: 'blackPageCost', label: 'blackPageCost', format: '%.5f €', css_class: text-right}
                    - { property: 'blackTonerPrice', label: 'blackTonerPrice', format: '%.2f €', css_class: text-right}
                    - { property: 'colorTonerPrice', label: 'colorTonerPrice', format: '%.25f €', css_class: text-right}
                    - { property: 'stock', label: 'stock' }
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic Information', icon: 'pencil' }
                    - { property: 'description', css_class: 'col-sm-4', label: 'description' }
                    - { property: 'subtitle', css_class: 'col-sm-4', label: 'subtitle' }
                    - { property: 'maker', css_class: 'col-sm-4', label: 'maker', type_options: { required: true } }
                    - { property: 'technology', css_class: 'col-sm-6', label: 'technology', type_options: { required: true } }
                    - { property: 'recomendedVolume', css_class: 'col-sm-6', label: 'recomendedVolume' , type_options: { required: true }}
                    - { type: 'section', label: 'configurer settings', icon: 'warning', help: 'configurer data help' }
                    - { property: 'functionality', css_class: 'col-sm-6', label: 'functionality', type_options: { required: true } }
                    - { property: 'chromaType', css_class: 'col-sm-6', label: 'chromaType', type_options: { required: true } }
                    - { property: 'format', css_class: 'col-sm-6', label: 'format', type_options: { required: true } }
                    - { property: 'pageRange', css_class: 'col-sm-6', label: 'pageRange', type_options: { required: true } }
                    - { property: 'recomended', label: 'recomended' , css_class: 'col-sm-6'}
                    - { property: 'stock', css_class: 'col-sm-6', label: 'stock', type_options: { required: true } }
                    - { type: 'section', label: 'aditional info', icon: 'warning', help: 'aditional info help' }
                    - { property: 'wifi', css_class: 'col-sm-3', label: 'wifi' }
                    - { property: 'airPrint', css_class: 'col-sm-2', label: 'doble cara' }
                    - { property: 'cloud', css_class: 'col-sm-2', label: 'ethernet' }
                    - { property: 'nfc', css_class: 'col-sm-2', label: 'impresión móvil' }
                    - { type: 'divider'}
                    - { property: 'aditionalInfo', type: 'ckeditor', label: 'aditionalInformation' }

                    - { type: 'group', css_class: 'col-sm-6', label: 'Product Details', icon: 'cube' }
                    - { property: 'cod', label: 'cod', type_options: { required: true } }
                    - { type: 'section', label: 'fixed price calculate', icon: 'warning', help: 'fixed price calculate help' }
                    - { property: 'price', label: 'price', type: 'money', type_options: { currency: 'EUR' }, css_class: 'col-sm-3' }
                    - { property: 'monitorizationPrice', type: 'money', type_options: { currency: 'EUR' }, css_class: 'col-sm-3', label: 'monitorization Price'}
                    - { property: 'instalationPrice', type: 'money', type_options: { currency: 'EUR' }, css_class: 'col-sm-3', label: 'installation Price'}
                    - { property: 'profit', label: 'profit', css_class: 'col-sm-3'}
                    - { property: 'carePack', css_class: 'col-sm-12', label: 'carePack', type_options: { required: true } }
                    - { type: 'section', label: 'variable price calculate', icon: 'warning', help: 'variable price calculate help' }
                    - { property: 'pageProfit', css_class: 'col-sm-3' }

                    - { type: 'divider' }
                    - { property: 'toners', css_class: 'col-sm-12', type_options: { required: true }}
                    - { property: 'drums', css_class: 'col-sm-6'}
                    - { property: 'parts', css_class: 'col-sm-6'}

                    - { type: 'group', css_class: 'col-sm-6', label: 'Manual de servicio', icon: 'paperclip' }
                    - { property: 'sheetFile', label: 'Archivo', type: 'vich_file' }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Attachments', icon: 'paperclip' }
                    - { property: 'imageFrontFile', label: 'imageFrontFile', type: 'vich_image' }
                    - { property: 'imageLateralFile', label: 'imageLateralFile', type: 'vich_image' }
                    - { property: 'imagePerspectiveFile', label: 'imagePerspectiveFile', type: 'vich_image' }







#                    - { property: 'ean', help: 'EAN-13 valid code. Leave empty if unknown.' }
#                    - { property: 'price', type: 'number' }
#                    - { type: 'section', label: 'Advanced Settings', icon: 'warning', help: 'Reserved for administrators use' }
#                    - { property: 'enabled', label: 'Published' }
#                    - { property: 'createdAt' }
#                    - { type: 'group', css_class: 'col-sm-8 new-row' }
#                    - { property: 'features' }
#                    - { type: 'group', css_class: 'col-sm-4' }
#                    - { property: 'tags' }
#                    - { type: 'group', css_class: 'col-sm-4', label: 'Attachments', icon: 'paperclip' }
#                    - { property: 'imageFile', type: 'vich_image', type_options: { required: true } }
