<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarePackRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CarePackRepository extends EntityRepository
{
    /**
     * @param CarePack $carePack
     * @param int $duration
     * @return float
     * @throws \Exception
     */
    public function getPriceByMonth(CarePack $carePack, $duration)
    {
        if (!$duration) {
            throw new \Exception('La duración de un servicio debe ser mayor que 0, error al calcular el precio mensual del carePack');
        }
        $profitDuration = intdiv($duration, 12) * 12;
        $profit = $this->getEntityManager()->getRepository('AppBundle:CarePackProfit')->findOneBy(['duration' => $profitDuration]);

        if (!$profit) {
            return $carePack->getPrice() / $duration;
        }

        return ($carePack->getPrice() + $carePack->getPrice() * $profit->getProfit()) / $duration;
    }
}
