<?php

namespace AppBundle\Entity\Repository;

use AppBundle\StaticsClass\Configurer;
use Doctrine\ORM\EntityRepository;
use Ivory\CKEditorBundle\Exception\Exception;

/**
 * ChromaTypeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ChromaTypeRepository extends EntityRepository
{

}
