<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Ivory\CKEditorBundle\Exception\Exception;

/**
 * FunctionalityRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class FunctionalityRepository extends EntityRepository
{

}
