<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MakerRepository.php
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your
 * own custom repository methods below.
 */
class InvoiceRepository extends EntityRepository {

    public function lastNumber($type) {
        $code = '/' . $type;
        $query = $this->createQueryBuilder('invoice')
            ->select('invoice')
            ->where("invoice.invoiceCode LIKE '%$code%'")
            ->setMaxResults(1);

        $query->orderBy('invoice.invoiceCode', 'DESC');
        $result = $query->getQuery()->getOneOrNullResult();

        if (!$result) {

            return 0;
        }

        return substr($result, -4);
    }

}