<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Ofert;
use AppBundle\Entity\SalesOrder;
use AppBundle\Entity\User;
use AppBundle\StaticsClass\SalesOrderStates;
use Doctrine\ORM\EntityRepository;

/**
 * MakerRepository.php
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class MakerRepository extends EntityRepository
{

}
