<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Machine;
use AppBundle\Entity\Ofert;
use Doctrine\ORM\EntityRepository;

/**
 * OfertRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class OfertRepository extends EntityRepository
{
    /**
     * @param Machine $machine
     * @param $duration
     * @param $pages
     * @param $colorPercent
     * @return Ofert
     */
    public function create(Machine $machine, $duration, $pages, $colorPercent)
    {
        $result = new Ofert();
        $result->setMachine($machine);
        $result->setDuration($duration);
        $result->setPages($pages);
        $result->setColorPercent($colorPercent);
        $result->setCreateAt(new \DateTime());

        return $result;
    }

    /**
     * @param Ofert $ofert
     */
    public function save(Ofert $ofert)
    {
        $this->getEntityManager()->persist($ofert);
        $this->getEntityManager()->flush();
    }
}
