<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * ChromaTypeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PageRangeRepository extends EntityRepository
{

    /**
     * @param $pages
     * @return mixed
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    public function getPageRangeByPages($pages)
    {
        $query = $this->createQueryBuilder('pr')
            ->select('pr')
            ->where('pr.start <= :pages')
            ->andWhere('pr.end >= :pages')
            ->setParameter(':pages', $pages);

        return $query->getQuery()->getSingleResult();
    }
}
