<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\ProductForPersistence;
use Doctrine\ORM\EntityRepository;

/**
 * ChromaTypeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProductForPersistenceRepository extends EntityRepository
{
    /**
     * @return array|null|ProductForPersistence[]
     */
    public function all(): ?array
    {
        return $this->findAll();
    }

    /**
     * @param int $id
     * @return ProductForPersistence|null|mixed
     */
    public function ofId(int $id): ?ProductForPersistence
    {
        return $this->find($id);
    }
}
