<?php


namespace AppBundle\StaticsClass;


final class Provinces
{
    const Provinces = [
        "Almería" => "Almería" ,
        "Cádiz" => "Cádiz",
        "Córdoba" => "Córdoba",
        "Granada" => "Granada",
        "Huelva" => "Huelva",
        "Jaén" => "Jaén",
        "Málaga" => "Málaga",
        "Sevilla" => "Sevilla",
        "Huesca" => "Huesca",
        "Teruel" => "Teruel",
        "Zaragoza" => "Zaragoza",
        "Asturias" => "Asturias",
        "Balears, Illes" => "Balears, Illes",
        "Palmas, Las" => "Palmas, Las",
        "Santa Cruz de Tenerife" => "Santa Cruz de Tenerife",
        "Cantabria" => "",
        "Ávila" => "Ávila",
        "Burgos" => "Burgos",
        "León" => "León",
        "Palencia" => "Palencia",
        "Salamanca" => "Salamanca",
        "Segovia" => "Segovia",
        "Soria" => "Soria",
        "Valladolid" => "Valladolid",
        "Zamora" => "Zamora",
        "Albacete" => "Albacete",
        "Ciudad Real" => "Ciudad Real",
        "Cuenca" => "Cuenca",
        "Guadalajara" => "Guadalajara",
        "Toledo" => "Toledo",
        "Barcelona" => "Barcelona",
        "Girona" => "Girona",
        "Lleida" => "Lleida",
        "Tarragona" => "Tarragona",
        "Alicante/Alacant" => "Alicante/Alacant",
        "Castellón/Castelló" => "Castellón/Castelló",
        "Valencia/València" => "Valencia/València",
        "Badajoz" => "Badajoz",
        "Cáceres" => "Cáceres",
        "Coruña, A" => "Coruña, A",
        "Lugo" => "Lugo",
        "Ourense" => "Ourense",
        "Pontevedra" => "Pontevedra",
        "Madrid" => "Madrid",
        "Murcia" => "Murcia",
        "Navarra" => "Murcia",
        "Araba/Álava" => "Araba/Álava",
        "Bizkaia" => "Bizkaia",
        "Gipuzkoa" => "Gipuzkoa",
        "Rioja, La" => "Rioja, La",
        "Ceuta" => "Ceuta",
        "Melilla" => "Melilla",
    ];
}